version: "3.9"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: todo-frontend
    ports:
      - "5173:5173"       
    volumes:
      - .:/app                 
      - /app/node_modules 
    environment:
      - CHOKIDAR_USEPOLLING=true
      - WATCHPACK_POLLING=true
    restart: unless-stopped